name: CD
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Install Depencies
        run: npm install

      - name: Decode Signing Certificate
        run: |
          echo $APPLE_DEVELOPER_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
        env:
          APPLE_DEVELOPER_CERTIFICATE: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Build and Notarize
        run: npm run make -- --arch ${{ matrix.arch }}
        env:
          VITE_APPLE_ID: ${{ secrets.VITE_APPLE_ID }}
          VITE_APPLE_PASSWORD: ${{ secrets.VITE_APPLE_PASSWORD }}
          VITE_TEAM_ID: ${{ secrets.VITE_TEAM_ID }}

      - name: List out directory contents
        run: ls -la out

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          draft: true
          prerelease: true

      - name: Upload x64 Release Asset
        if: matrix.arch == 'x64'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/make/x64/BentoNews.zip
          asset_name: BentoNews-x64.zip
          asset_content_type: application/zip

      - name: Upload arm64 Release Asset
        if: matrix.arch == 'arm64'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/make/arm64/BentoNews.zip
          asset_name: BentoNews-arm64.zip
          asset_content_type: application/zip
